# Generated by Django 5.1 on 2024-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='post_vid/'),
        ),
    ]
