# Generated by Django 5.1 on 2024-08-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0004_alter_post_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_loggedIn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
