# Generated by Django 5.1 on 2024-08-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0014_friendaccepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='accepted_at',
        ),
        migrations.AddField(
            model_name='friendaccepted',
            name='accepted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
