# Generated by Django 5.1 on 2024-08-11 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0015_remove_friend_accepted_at_friendaccepted_accepted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='friendaccepted',
            name='friend',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='sm.friend'),
        ),
        migrations.CreateModel(
            name='FriendsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.friend')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationCommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.comment')),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.like')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationFriendAccepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('friend_accepted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.friendaccepted')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.like')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.notification')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPostPosted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originator', models.IntegerField()),
                ('message', models.TextField()),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.notification')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sm.post')),
            ],
        ),
    ]
