# Generated by Django 5.1 on 2024-08-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0018_friendaccepted_of_friend_friendaccepted_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
    ]
