# Generated by Django 5.1 on 2024-08-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0019_alter_friend_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendaccepted',
            name='friend',
        ),
    ]
