# Generated by Django 5.1 on 2024-08-21 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sm', '0021_remove_notificationcommentpost_like_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationcommentpost',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notificationcommentpost',
            name='comment_by',
        ),
        migrations.RemoveField(
            model_name='notificationcommentpost',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationfriendaccepted',
            name='friend_accepted',
        ),
        migrations.RemoveField(
            model_name='notificationfriendaccepted',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationlikepost',
            name='like',
        ),
        migrations.RemoveField(
            model_name='notificationlikepost',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationpostposted',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='notificationpostposted',
            name='post',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FriendsNotification',
        ),
        migrations.DeleteModel(
            name='NotificationCommentPost',
        ),
        migrations.DeleteModel(
            name='NotificationFriendAccepted',
        ),
        migrations.DeleteModel(
            name='NotificationLikePost',
        ),
        migrations.DeleteModel(
            name='NotificationPostPosted',
        ),
    ]
