# Generated by Django 5.1 on 2024-08-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0023_rename_user_notification_to_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
