# Generated by Django 5.1 on 2024-08-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sm', '0027_userprofile_full_name_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedpost',
            old_name='author_of_post',
            new_name='user',
        ),
    ]
